spring:
  application:
    name: uptention

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone=UTC:

  cloud:
    aws:
      s3:
        region: ap-northeast-2  # 버킷 위치
        enabled: true #  Spring Cloud AWS 스타터가 S3 관련 빈 자동 구성
      credentials:
        access-key: ${S3_ACCESS_TOKEN}
        secret-key: ${S3_SECRET_TOKEN}
  
  profiles:
    group:
      local:
        - local
      prod:
        - prod
      test:
        - test

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html

aws:
  s3:
    bucket: uptention
