spring:
  application:
    name: uptention

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTF

  profiles:
    group:
      local:
        - local
      prod:
        - prod
      test:
        - test

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
