spring:
  application:
    name: uptention

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  profiles:
    group:
      local:
        - local
      prod:
        - prod

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
