spring:
  application:
    name: uptention

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone=UTC:

  cloud:
    aws:
      s3:
        region: ap-northeast-2  # 버킷 위치
        enabled: true #  Spring Cloud AWS 스타터가 S3 관련 빈 자동 구성
      credentials:
        access-key: ${S3_ACCESS_TOKEN}
        secret-key: ${S3_SECRET_TOKEN}

  jwt:
    secret: ${JWT_SECRET_KEY}

  servlet:
    multipart:
      max-file-size: 5MB # 파일 하나 당 최대 용량
      max-request-size: 25MB # 모든 파일의 최대 용량

  profiles:
    group:
      local:
        - local
      prod:
        - prod
      test:
        - test

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html

aws:
  s3:
    bucket: uptention
    cloudfront-domain: ddnwvg9t77g5o.cloudfront.net

solana:
  network: ${SOLANA_NETWORK}
  rpc-url: ${SOLANA_RPC_URL}
  websocket-url: ${SOLANA_WEBSOCKET_URL}
  company-wallet: ${SOLANA_COMPANY_WALLET}
  token-program-id: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
  work-token-mint: ${WORK_TOKEN_MINT}

logging:
  level:
    com:
      otoki:
        uptention:
          solana:
            service=DEBUG:

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
