spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/uptention?useSSL=false&useUnicode=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: local
    password: local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: local
    password: local

solana:
  network: ${SOLANA_NETWORK}
  rpc-url: ${SOLANA_RPC_URL}
  websocket-url: ${SOLANA_WEBSOCKET_URL}
  company-wallet: ${SOLANA_COMPANY_WALLET}
  token-program-id: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
  work-token-mint: ${WORK_TOKEN_MINT}
