[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
uptention = "6EU2JYdEjdQgXMQH2m5UFXn6p4J1zVL73M65PkvwgwDR"

[programs.devnet]
uptention = "6EU2JYdEjdQgXMQH2m5UFXn6p4J1zVL73M65PkvwgwDR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ubuntu/keys/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000  # 10초
